[package]
name = "hyprland-autodim"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
hyprland = "0.3.8"

[build-dependencies]
clap = { version = "4.3.19", features = ["derive"] }
clap_mangen = "0.2.12"
