[package]
name = "hyprdim"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
ctrlc = { version = "3.4.0", features = ["termination"] }
hyprland = "0.3.8"

[build-dependencies]
clap = { version = "4.3.19", features = ["derive"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.12"
